### ISSUE TITLE
anyway to set language?

### ISSUE THREAD

**Issue by MingOf** [RediSearch/redisearch-go#101]

**Comment by filipecosta90** [comment]
Hi there @MingOf yes. Via https://pkg.go.dev/github.com/RediSearch/redisearch-go@v1.1.0/redisearch#IndexingOptions

You can then use [Client.IndexOptions() method](https://pkg.go.dev/github.com/RediSearch/redisearch-go@v1.1.0/redisearch#Client.IndexOptions) to Index the document

**Comment by MingOf** [comment]
thanks a lot. I finally found it in source code
