### ISSUE TITLE
Update the document with examples 

### ISSUE THREAD

**Issue by AvitalFineRedis** [RediSearch/redisearch-go#122]

**Comment by AvitalFineRedis** [comment]
https://yourbasic.org/golang/package-documentation/
https://blog.golang.org/examples

**Comment by filipecosta90** [comment]
@AvitalFineRedis notice that we already follow this way of documentation, as exemplified in https://github.com/RediSearch/redisearch-go/blob/master/redisearch/example_client_test.go

Is this issue just to keep track of the extension of examples?

**Comment by AvitalFineRedis** [comment]
Yes, sure @filipecosta90 
I want to add more documentation and more examples :)
