### ISSUE TITLE
Question: `pinyin` of `Chinese` text search

### ISSUE THREAD

**Issue by Mrliu8023** [RediSearch/redisearch-go#127]
A text like "jichusheshihuanjingkongdiaowenduxunjianyijcsshjkdwdxjy", Are there any way to query it by using `wendu` or `wd`?

**Comment by gkorland** [comment]
@Mrliu8023 RediSerach only supports prefix search for now.
See: 
https://github.com/RediSearch/RediSearch/issues/2081
https://github.com/RediSearch/RediSearch/issues/348
https://github.com/RediSearch/RediSearch/issues/1922

**Comment by gkorland** [comment]
Duplicate: https://github.com/RediSearch/RediSearch/issues/2263
