### ISSUE TITLE
Create Index using JSON

### ISSUE THREAD

**Issue by xegea** [RediSearch/redisearch-go#138]
Is it possible to create an index using ON JSON SCHEMA as I do in Redis using Redisearch + RedisJSON together?

Example:
FT.CREATE idx:title ON JSON SCHEMA $.Title AS title TEXT

**Comment by gkorland** [comment]
```
NewIndexDefinition().SetIndexOn(JSON)
```
https://github.com/RediSearch/redisearch-go/pull/111
