### ISSUE TITLE
Index a document with Numberic Field,  but get string type from Search.

### ISSUE THREAD

**Issue by xjplke** [RediSearch/redisearch-go#150]
I create  a schema and  a document with a numberic field, and index this doc.
Then I use the Search method to query it, but I get a value of string type from this field.
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/5140244/161771070-aa370101-c0b1-4ca8-9575-8d00dddc8df8.png">

**Comment by Avital-Fine** [comment]
@xjplke Hey!
That happens because redis returns strings by default. You need to convert it to numeric value by yourself.
