### ISSUE TITLE
Error parsing Aggregate Reply

### ISSUE THREAD

**Issue by adiongue** [RediSearch/redisearch-go#154]
I have tried to use group with reducer`TOLIST`, redisearch.GroupByReducerToList but I got the following error

My request: `redisearch.AggregateQuery{Max: 100000}.GroupBy(redisearch.GroupBy{Fields: []string{"@name"}, Reducers: []redisearch.Reducer{{Alias: "ids", Name: redisearch.GroupByReducerToList, Args: []string{"@b_id"}}}`

Error:
`Error parsing Aggregate Reply: redigo: unexpected element type for Strings, got type []interface {} on reply position 4`

Do you know if there is another way to do this request please ?

Thank!

**Comment by Avital-Fine** [comment]
@adiongue I fixed it in #157. Now the returned type is different but it makes more sense to me.
Let me know if you still having trouble with that!

**Comment by adiongue** [comment]
thank you @Avital-Fine

**Comment by adiongue** [comment]
@Avital-Fine I use the last version of master but the aggregate function still returns `[][]string`

**Comment by Avital-Fine** [comment]
Use `AggregateQuery()` (I couldn't break it so I deprecated the old version)
