### ISSUE TITLE
How to reference existing JSON index

### ISSUE THREAD

**Issue by marcoroganovic** [RediSearch/redisearch-go#156]
Hi,

I have read through the other issues but I couldn't find answer to this question. How to let client know to use JSON instead of default HASH?

So basically I have created index in other language, and I need to consume that index in Go using this package, but search queries don't work when I have switched from HASH to JSON definition (during creation in other language).

Best,
Marko

**Comment by Avital-Fine** [comment]
Hey! You can use [this](https://github.com/RediSearch/redisearch-go/blob/5c6afe85226f625c202899e1bb5926afbda64037/redisearch/index.go#L62) method to create the index with ON JSON instead of ON HASH
