### ISSUE TITLE
how was the connection pool closed? 

### ISSUE THREAD

**Issue by ericfengchao** [RediSearch/redisearch-go#16]
https://github.com/RediSearch/redisearch-go/blob/master/redisearch/client.go#L42
i suppose this resource requires disposal on system reload or sth? to avoid idle conn pileup at redis side.

**Comment by filipecosta90** [comment]
Hi there @ericfengchao , you're right and this can indeed cause service disruption on Redis if we reach a point in which we saturate the Redis server with lots of idle connections. 
As a quick fix for making sure this does not happen, make sure to have Redis configured to close the connection with the client if the client is idle for many seconds ( Please see section "Client timeouts" [here](https://redis.io/topics/clients) ). 
We will bring this issue to the next redisearch-go release planning and solve it for sure ( for example by enabling a constructor that receives a connection pool ) 
Thanks for bringing this up :)
