### ISSUE TITLE
Proposal to mark a new release

### ISSUE THREAD

**Issue by SuganPrabu96** [RediSearch/redisearch-go#166]
I'm trying out Redis Vector Similarity Search and found that one of the recent commits of redisearch-go has the support for the fields that are required. However, there isn't a release version that includes this. It would be very helpful to have a release version that I can pin to, and use. Thank you!

**Comment by chayim** [comment]
Sounds like a reasonable ask! Assigning to myself, and let's try and get you one this week.

**Comment by chayim** [comment]
closing - we released one ;)
