### ISSUE TITLE
Vector similarity

### ISSUE THREAD

**Issue by Leterax** [RediSearch/redisearch-go#168]
Is there a possibility to use [vector similarity search](https://redis.io/docs/stack/search/reference/vectors/)?
I wasn't able to find it in the docs.
Thanks!

**Comment by gkorland** [comment]
@Leterax please notice the code already supports VecSim see: https://github.com/RediSearch/redisearch-go/pull/151
A new official version should be released soon.

**Comment by gkorland** [comment]
ref https://github.com/RediSearch/redisearch-go/issues/146

**Comment by Leterax** [comment]
Thank you very much, that's great to hear! 
You probably don't have a eta on the official release right? Working with the PR should be fine until then. :)

**Comment by Leterax** [comment]
The test in #151 uses the internal connection pool and HSET. I assume the user is supposed to create documents using 
`redisearch.NewDocument(fmt.Sprintf("image:%s", imageName), 1.0).Set("v", vector).Set("name", imageName)`
and index them using `r.client.Index([]redisearch.Document{doc}...)`?

**Comment by chayim** [comment]
Closing - we released [2.1.0](https://github.com/RediSearch/redisearch-go/releases/tag/v2.1.0)
