### ISSUE TITLE
how to create connection different port with the NewDocument function

### ISSUE THREAD

**Issue by victormongi** [RediSearch/redisearch-go#17]
How to create connection different port with the NewDocument function?

**Comment by ericfengchao** [comment]
not exactly following your question. Do you mean that you want to index a document using a specific connection? like using only master connection for indexing documents while master/slave for querying?

**Comment by filipecosta90** [comment]
hi there @victormongi and @ericfengchao, closing this issue since this seems to be more like a question than a bug report/improvement proposal. Please do open it again if you feel this is not the case :)
