### ISSUE TITLE
Has this client alter schema support?

### ISSUE THREAD

**Issue by Felixls** [RediSearch/redisearch-go#25]
https://oss.redislabs.com/redisearch/Commands/#ftalter

**Comment by filipecosta90** [comment]
hi there @Felixls, not yet but this is a simple command. Are you interested in doing it and we review it :) or can we go ahead and add it?

**Comment by Felixls** [comment]
I did already in my fork, but is togheter with another fix (LIMIT thing you know) https://github.com/Felixls/go-mysql-redisearch

**Comment by filipecosta90** [comment]
> I did already in my fork, but is togheter with another fix (LIMIT thing you know)
> 
> https://github.com/Felixls/redisearch-go

Do you want to split them and PR the alter schema support? :)

**Comment by Felixls** [comment]
:+1: on it, in 20 min I will post the PR in here

**Comment by filipecosta90** [comment]
hi there @Felixls you want me to jump in and split the code? :) 
No rush on our side, but we would like to integrate your changes

**Comment by filipecosta90** [comment]
@Felixls merged your PR together with the small changes requested :+1: :) thank you for bringing this issue forward.
