### ISSUE TITLE
FT.SYNADD FT.SYNUPDATE FT.SYNDUMP support

### ISSUE THREAD

**Issue by filipecosta90** [RediSearch/redisearch-go#42]

**Comment by dengliming** [comment]
Are you still working on this issue? @filipecosta90

**Comment by filipecosta90** [comment]
> Are you still working on this issue? @filipecosta90

haven't started yet. Appreciate if you want to push it :+1:

**Comment by dengliming** [comment]
Got it, I will push it recently.

**Comment by filipecosta90** [comment]
solved by #55 . Thanks @dengliming :+1:
