### ISSUE TITLE
NewSchema ignores opts arg

### ISSUE THREAD

**Issue by kind84** [RediSearch/redisearch-go#56]
https://github.com/RediSearch/redisearch-go/blob/76b1c66443a741956e7e4ad60f3c2f78f4b68076/redisearch/schema.go#L165

That's why my options were not working :sweat_smile:

**Comment by filipecosta90** [comment]
hi there @kind84 thanks for reporting it. Just confirmed that this is present across all released versions. We'll fix it and include proper testing to ensure it wont happen again :)

**Comment by filipecosta90** [comment]
@kind84 , the PR #58 should fix it :+1:

**Comment by filipecosta90** [comment]
hi there @kind84 , [version 0.9.2](https://github.com/RediSearch/redisearch-go/releases/tag/0.9.2) has this fix in place :) Thanks for reporting it
