### ISSUE TITLE
FT.SEARCH support GEOFILTER and FILTER

### ISSUE THREAD

**Issue by dengliming** [RediSearch/redisearch-go#61]
See [https://oss.redislabs.com/redisearch/Commands.html#ftsearch](https://oss.redislabs.com/redisearch/Commands.html#ftsearch)

**Comment by filipecosta90** [comment]
hi there @dengliming , I believe coupled with this issue it is supporting geofields on the go client ( #11 ), which we're targetting for the next release =)

**Comment by filipecosta90** [comment]
fixed by #63 . thanks @dengliming :+1:
