### ISSUE TITLE
garyburd/redigo is no longer the default Redigo source

### ISSUE THREAD

**Issue by lucasvfventura** [RediSearch/redisearch-go#8]
Trying to build my application that uses redisearch-go using GO 1.11 modules (outside the GOPATH) generated the following error:
\pkg\mod\github.com\garyburd\redigo@v2.0.0+incompatible\redis\pool.go:28:2: use of internal package github.com/gomodule/redigo/internal not allowed

According to the issue https://github.com/heroku/x/issues/34 , it seems that all Redigo development was moved to github.com/gomodule/redigo. 

The issue might be fixed by updating all references to Redigo to the current source.

**Comment by filipecosta90** [comment]
hi there @lucasvfventura, thank you for pointing this out. This has been addressed and can be checked in master and should be bundled in a release very soon.
