### ISSUE TITLE
Allow passing an existing redigo pool to a new redisearch.Client

### ISSUE THREAD

**Issue by sinni800** [RediSearch/redisearch-go#9]
If I want to use a mixture of redisearch and regular redis queries, I will currently need to create two connection pools that act seperately. Either let me create clients from single connections or from connection pools. Let me handle my connections myself, this should be the "idiomatic go way" anyway.

**Comment by filipecosta90** [comment]
hi there @sinni800 , you're right and we should address this very soon. 
Thanks for bringing this up :+1: 
also, please see the added comment on #16

**Comment by filipecosta90** [comment]
hi there @sinni800 , this has been solved in #51.
