### ISSUE TITLE
support for redisearch v2.0

### ISSUE THREAD

**Issue by shumin1027** [RediSearch/redisearch-go#91]
when to support for redisearch v2.0 ?

**Comment by filipecosta90** [comment]
Hi there @shumin1027 , the version [v2.0.0-M3](https://github.com/RediSearch/redisearch-go/releases/tag/v2.0.0-M3) added support for it on Aug 18.
Nonetheless, given it was tagged as a pre-release it's not considered the latest version when fetching dependencies on your projects. We will fix this shortly with the release of v2.0.0. 
Let's keep this issue open until we do so.

**Comment by filipecosta90** [comment]
Hi there @shumin1027 we've just released [v2.0.1](https://github.com/RediSearch/redisearch-go/releases/tag/v2.0.1). 
We've also included some documentation examples on how to follow the data written in hashes (HSET) and automatically index it.

Here's one: https://godoc.org/github.com/RediSearch/redisearch-go/redisearch#example-Client-CreateIndexWithIndexDefinition-Phonetic

Closing this issue. Feel free to re-open it if you need further examples.

**Comment by shumin1027** [comment]
@filipecosta90 
thank you very much，we will update redisearch to v2.0
