### ISSUE TITLE
I need to drop the index,but not found this func

### ISSUE THREAD

**Issue by is-a-gamer** [RediSearch/redisearch-go#94]
Sometimes I just need to delete a separate index and should not use it `client.Drop()`

**Comment by filipecosta90** [comment]
Hi there @is-a-gamer , agree.
Given that for v1.6 and v2.0 we have FT.DROP and FT.DROPINDEX I would take this opportunity to add:
- `DropByName( string indexName, bool keepDocs )` - maps to https://oss.redislabs.com/redisearch/Commands/#ftdrop. We can warn that as of v2.0 DropByName and Drop are deprecated.
- `DropIndex( string indexName, bool deleteDocs )` - maps to https://oss.redislabs.com/redisearch/Commands/#ftdropindex

wdyt @gkorland @MeirShpilraien ?

------------------

Apart from it, @is-a-gamer do you want to submit a PR, or do you want us to do it? Happy to review :)

**Comment by MeirShpilraien** [comment]
@filipecosta90 why not stick to the same name as in the api, i.e, Drop and DropIndex?

**Comment by filipecosta90** [comment]
> @filipecosta90 why not stick to the same name as in the api, i.e, Drop and DropIndex?

Drop() is already taken since the beginning of the client. Given we can't overload we need a different name :)

**Comment by is-a-gamer** [comment]
> Apart from it, @is-a-gamer do you want to submit a PR, or do you want us to do it? Happy to review :)

No

I added a method to the client.go
```Golang
func (i *Client) DropIndex(deleteDocument bool) (err error) {
	conn := i.pool.Get()
	defer conn.Close()

	if deleteDocument {
		_, err = conn.Do("FT.DROPINDEX", i.name, "DD")
	} else {
		_, err = conn.Do("FT.DROPINDEX", i.name)
	}
	return
}
```
Although it can work normally in my process, I think you should do it more correctly

**Comment by filipecosta90** [comment]
> > @filipecosta90 why not stick to the same name as in the api, i.e, Drop and DropIndex?
> 
> Drop() is already taken since the beginning of the client. Given we can't overload we need a different name :)

@MeirShpilraien, bumping this one. I believe we should go with due to the reasons discussed above:

- DropByName( string indexName, bool keepDocs ) - maps to https://oss.redislabs.com/redisearch/Commands/#ftdrop. We can warn that as of v2.0 DropByName and Drop are deprecated.
 - DropIndex( string indexName, bool deleteDocs ) - maps to https://oss.redislabs.com/redisearch/Commands/#ftdropindex

**Comment by shumin1027** [comment]
@filipecosta90 
how about
```golang
// Deletes the index.
// By default, FT.DROPINDEX does not delete the document hashes associated with the index. Adding the DD option deletes the hashes as well.
func (i *Client) dropIndex(keepdocs bool) error {
	conn := i.pool.Get()
	defer conn.Close()

	var err error = nil
	if keepdocs {
		_, err = conn.Do("FT.DROPINDEX", i.name)
	} else {
		_, err = conn.Do("FT.DROPINDEX", i.name, "DD")
	}
	return err
}

// Deletes the index and deletes the hashes as well
func (i *Client) DropIndex() error {
	return i.dropIndex(false)
}

// Deletes the index but does not delete the document hashes associated with the index
func (i *Client) DropIndexWithKeepdocs() error {
	return i.dropIndex(true)
}

```

**Comment by filipecosta90** [comment]
> @filipecosta90
> how about
> 
> ```go
> // Deletes the index.
> // By default, FT.DROPINDEX does not delete the document hashes associated with the index. Adding the DD option deletes the hashes as well.
> func (i *Client) dropIndex(keepdocs bool) error {
> 	conn := i.pool.Get()
> 	defer conn.Close()
> 
> 	var err error = nil
> 	if keepdocs {
> 		_, err = conn.Do("FT.DROPINDEX", i.name)
> 	} else {
> 		_, err = conn.Do("FT.DROPINDEX", i.name, "DD")
> 	}
> 	return err
> }
> 
> // Deletes the index and deletes the hashes as well
> func (i *Client) DropIndex() error {
> 	return i.dropIndex(false)
> }
> 
> // Deletes the index but does not delete the document hashes associated with the index
> func (i *Client) DropIndexWithKeepdocs() error {
> 	return i.dropIndex(true)
> }
> ```

@shumin1027 I would use `DropIndex( string indexName, bool deleteDocs )` for one reason. Please notice that `DD` argument maps directly to `deleteDocs` argument. On your function signature we have the inverse `keepdocs` which might confuse users.

**Comment by filipecosta90** [comment]
@is-a-gamer @shumin1027 do you guys want to propose a PR. Will gladly review it :)
