### ISSUE TITLE
 add `Deprecate` comment for the deprecated commands

### ISSUE THREAD

**Issue by shumin1027** [RediSearch/redisearch-go#95]
many deprecated commands in redisearch 2.0 ，but the code didn't add `Deprecate` comment
https://oss.redislabs.com/redisearch/Commands/#deprecated_commands

**Comment by filipecosta90** [comment]
Hi there @shumin1027 , as on version 1.1.0 of this client we've added the redisearch v2 deprecation notices. Example of https://pkg.go.dev/github.com/RediSearch/redisearch-go@v1.1.0/redisearch#Client.AddHash 
Thank you for reporting this! :)
